baseURL = "https://hyennnlog.kr/"
languageCode = "ko-kr"
title = "HYENNN"
theme = "hugo-coder"

[pagination]
  pagerSize = 10

[params]
  author = "kimhyejin"
  description = "hyennn.log"

  customCSS = ["css/custom.css", "css/photos.css"]

[menu]

  [[menu.main]]
    name = "소개"
    url = "/about/"
    weight = 10


  [[menu.main]]
    name = "영화"
    url = "/cinema/"
    weight = 20

  [[menu.main]]
    name = "책"
    url = "/book/"
    weight = 30


  [[menu.main]]
    name = "필름"
    url = "/photos/"
    weight = 40

  [[menu.main]]
    name = "그림"
    url = "/sketch/"
    weight = 50

  [[menu.main]]
    name = "일기"
    url = "/diary/"
    weight = 60

  [[menu.main]]
    name = "🎞️"
    url = "/kimgyeul/"
    weight = 70

[markup.goldmark.renderer]
  unsafe = true
