baseURL = "https://hyennnlog.kr/"
languageCode = "ko-kr"
title = "KIMHYEJIN"
theme = "hugo-coder"

[pagination]
  pagerSize = 10

[params]
  author = "kimhyejin"
  description = "hyennn.log"
  
  customCSS = ["css/custom.css", "css/photos.css"]


[menu]

  [[menu.main]]
    name = "About。"
    url = "/about/"
    weight = 10


  [[menu.main]]
    name = "Cinema-note°"
    url = "/cinema/"
    weight = 20

  [[menu.main]]
    name = "Book-note。"
    url = "/book/"
    weight = 30


  [[menu.main]]
    name = "35mm-films°"
    url = "/photos/"
    weight = 40

  [[menu.main]]
    name = "Drawing-月間。"
    url = "/monthly-drawing/"
    weight = 50

  [[menu.main]]
    name = "Notes°"
    url = "/diary/"
    weight = 60

  [[menu.main]]
    name = "/et cetera.."
    url = "/kimgyeul/"
    weight = 70

[markup.goldmark.renderer]
  unsafe = true
